export const STRENGTH_LABELS: Record<string, string> = {
  'strength.grammar_explanation':  'Grammar Explanation',
  'strength.pronunciation':        'Pronunciation Practice',
  'strength.vocabulary_volume':    'Vocabulary Building',
  'strength.cultural_context':     'Korean Culture',
  'strength.real_life_phrases':    'Real-life Phrases',
  'strength.slang_trendy':         'Slang & Trends',
  'strength.formal_language':      'Honorifics & Formal',
  'strength.kpop_kdrama_context':  'K-Pop / K-Drama',
  'strength.exam_focused':         'TOPIK Prep',
  'format.flashcard':              'Flashcards',
  'format.video_lecture':          'Video Lectures',
  'format.native_speaker_clips':   'Native Speaker Clips',
  'format.live_action_drama':      'Live-action Drama',
  'format.whiteboard_explanation': 'Whiteboard Lessons',
  'format.downloadable_pdf':       'Downloadable PDF',
  'format.subtitles_dual':         'Dual Subtitles',
  'fit.needs_structure':           'Needs Structure',
  'fit.casual_learner':            'Casual Learning',
  'fit.kpop_fan':                  'K-Pop / K-Culture Fans',
  'fit.career_focused':            'Career / Exam Focus',
  'fit.shy_speaker':               'Shy Speakers',
  'ux.offline_available':          'Offline Access',
  'ux.gamification':               'Gamification',
  'ux.short_videos':               'Short Videos (5–15 min)',
  'ux.multilingual_interface':     'Multilingual UI',
  'social.live_class_option':      'Live Classes',
  'social.community_forum':        'Learning Community',
  // Limitations
  'limit.weak_in_speaking':              'Weak in Speaking',
  'limit.weak_in_writing':               'Weak in Writing',
  'limit.weak_in_advanced':              'Lacks Advanced Content',
  'limit.weak_in_grammar':               'Lacks Grammar Explanation',
  'limit.weak_in_reading':               'Weak in Reading',
  'limit.no_human_feedback':             'No Human Feedback',
  'limit.voice_recognition_unreliable':  'Unreliable Voice Recognition',
  'limit.requires_supplementary':        'Best with Supplements',
  'limit.no_certification':              'No Certificate',
};
